# Generated by Django 5.1.1 on 2024-10-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'verbose_name': 'Ссылка на канал', 'verbose_name_plural': 'Ссылки на каналы'},
        ),
        migrations.AddField(
            model_name='url',
            name='channel_chat_id',
            field=models.CharField(default=0, max_length=255, verbose_name='Чат айди канала, взятый из @username_to_id_bot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='url',
            name='channel_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя канала'),
        ),
        migrations.AlterField(
            model_name='url',
            name='channel_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на канал'),
        ),
    ]
